site:
  title:      mriddle.com
  slogan:     It\'s a feature not a bug!
  about:      Hi there! My name is Matthew Riddle and this is my log of programming related solutions and tutorials that I have written or found on the net which have proven useful. It's kept primary for my own memory but is shared to help others.

  rss_title:  mriddle.com RSS feed
  rss_author: mriddle
  rss_about:  Feeding hungry devs

  linked_in:  in/mriddle
  github:       mriddle
  twitter:    mriddle89

  app_name:   blog
  app_repo:   git@github.com:mriddle/blog.git
  app_server: 203.143.82.172

  deploy_user: admin